# Site settings
title: PACS Development Playbook
name:  PACS Development Playbook
email: icam@gsa.gov
author:
    name: FICAM
description: PACS Guidance
baseurl: '/ficam-pacs'
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  lachellel
highlighter: rouge
branch: master

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /ficam-pacs/img/logo.png
logoalt: Federal Identity Credential and Access Management

ficam_playbooks_url: /ficam-guides/

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: program-guides
  description: FICAM Playbook - Physical Access Control
  url: https://github.com/gsa/ficam-pacs

# Build settings
markdown: kramdown

exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

navigation:
- text: Home
  url: index.html
  internal: true
  coll: false
- text: Step 1 - Begin Planning
  url: 1_step-1
  internal: true
  coll: false
- text: Step 2 - Begin Requirements and Design
  url: 2_step-2
  internal: true
  coll: false
- text: Step 3 - Design Solution Architecture
  url: 3_step-3
  internal: true
  coll: false
- text: Step 4 - Review Solution Components
  url: 4_step-4
  internal: true
  coll: false
- text: Step 5 - Identify Common Design Characteristics
  url: 5_step-5
  internal: true
  coll: false
- text: Step 6 - Begin Building Architecture
  url: 6_step-6
  internal: true
  coll: false
- text: Step 7 - Determine Automated Provisioning Approach
  url: 7_step-7
  internal: true
  coll: false
- text: Step 8 - Implement
  url: 8_step-8
  internal: true
  coll: false
- text: Step 9 - Operate and Maintain
  url: 9_step-9
  internal: true
  coll: false
- text: Step 10 - Create Common Physical Access Scenarios
  url: 10_step-10
  internal: true
  coll: false
- text: Contribute
  url: contribute
  internal: true
  coll: false
include:
- _stylesheets
- _javascript



# Custom site configuration
lang: en
